// Mocks generated by Mockito 5.1.0 from annotations
// in cake/test/modules/authentication/domain/usecases/sign_up_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:cake/modules/authentication/domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

import 'sign_up_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUser_0 extends _i1.Fake implements _i2.User {}

/// A class which mocks [AuthenticationRepositoryTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepositoryTest extends _i1.Mock
    implements _i3.AuthenticationRepositoryTest {
  MockAuthenticationRepositoryTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User> signIn(_i2.User? user) =>
      (super.noSuchMethod(Invocation.method(#signIn, [user]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i4.Future<_i2.User>);
  @override
  _i4.Future<_i2.User> signUp(_i2.User? user) =>
      (super.noSuchMethod(Invocation.method(#signUp, [user]),
              returnValue: Future<_i2.User>.value(_FakeUser_0()))
          as _i4.Future<_i2.User>);
}
